// AUTO-GENERATED by scripts/generate-poster-previews.mjs — do not edit by hand.
// Maps each full-res poster master (png URL) to its small web preview (webp URL).

const POSTER_PREVIEWS: Record<string, string> = {
  "/posters/real_math_real_decisions_24x36_3600x5400.png": "/posters/previews/real_math_real_decisions_24x36_3600x5400.webp",
  "/posters/not_just_answers_3600x5400.png": "/posters/previews/not_just_answers_3600x5400.webp",
  "/posters/serious_math_different_path_3600x5400.png": "/posters/previews/serious_math_different_path_3600x5400.webp",
  "/posters/compared_to_what_24x36_3600x5400.png": "/posters/previews/compared_to_what_24x36_3600x5400.webp",
  "/posters/per_what_24x36_3600x5400.png": "/posters/previews/per_what_24x36_3600x5400.webp",
  "/posters/what_are_we_measuring_final_2026_05_13_24x36_3600x5400.png": "/posters/previews/what_are_we_measuring_final_2026_05_13_24x36_3600x5400.webp",
  "/posters/what_does_this_prove_24x36_3600x5400.png": "/posters/previews/what_does_this_prove_24x36_3600x5400.webp",
  "/posters/what_does_this_prove_2_24x36_3600x5400.png": "/posters/previews/what_does_this_prove_2_24x36_3600x5400.webp",
  "/posters/who_is_missing_24x36_3600x5400.png": "/posters/previews/who_is_missing_24x36_3600x5400.webp",
  "/posters/is_that_reasonable_24x36_3600x5400.png": "/posters/previews/is_that_reasonable_24x36_3600x5400.webp",
  "/posters/where_did_the_number_come_from_24x36_3600x5400.png": "/posters/previews/where_did_the_number_come_from_24x36_3600x5400.webp",
  "/posters/what_is_the_claim_24x36_3600x5400.png": "/posters/previews/what_is_the_claim_24x36_3600x5400.webp",
  "/posters/correlation_is_not_causation_24x36_3600x5400.png": "/posters/previews/correlation_is_not_causation_24x36_3600x5400.webp",
  "/posters/a_graph_is_an_argument_24x36_3600x5400.png": "/posters/previews/a_graph_is_an_argument_24x36_3600x5400.webp",
  "/posters/bad_survey_bad_data_24x36_3600x5400.png": "/posters/previews/bad_survey_bad_data_24x36_3600x5400.webp",
  "/posters/scale_changes_the_story_24x36_3600x5400.png": "/posters/previews/scale_changes_the_story_24x36_3600x5400.webp",
  "/posters/a_decision_is_a_tradeoff_24x36_3600x5400.png": "/posters/previews/a_decision_is_a_tradeoff_24x36_3600x5400.webp",
  "/posters/weighting%20is%20a%20_24x36_3600x5400.png": "/posters/previews/weighting_is_a_24x36_3600x5400.webp",
  "/posters/know_the_user_3600x5400.png": "/posters/previews/know_the_user_3600x5400.webp",
  "/posters/every_model_leaves_something_out_24x36_3600x5400.png": "/posters/previews/every_model_leaves_something_out_24x36_3600x5400.webp",
  "/posters/test_the_tool_24x36_3600x5400.png": "/posters/previews/test_the_tool_24x36_3600x5400.webp",
  "/posters/the_tool_is_not_the_thinking_24x36_3600x5400.png": "/posters/previews/the_tool_is_not_the_thinking_24x36_3600x5400.webp",
  "/posters/ai_as_a_coach_in_learning_24x36_3600x5400.png": "/posters/previews/ai_as_a_coach_in_learning_24x36_3600x5400.webp",
  "/posters/dont_disappear_24x36_3600x5400.png": "/posters/previews/dont_disappear_24x36_3600x5400.webp",
  "/posters/ask_earlier_24x36_3600x5400.png": "/posters/previews/ask_earlier_24x36_3600x5400.webp",
  "/posters/proof_of_progress_24x36_3600x5400.png": "/posters/previews/proof_of_progress_24x36_3600x5400.webp",
  "/posters/stuck_work_the_help_path_24x36_3600x5400.png": "/posters/previews/stuck_work_the_help_path_24x36_3600x5400.webp",
  "/posters/revision_is_the_work_24x36_3600x5400.png": "/posters/previews/revision_is_the_work_24x36_3600x5400.webp",
  "/posters/10_things_0_talent_respect_final_24x36_3600x5400.png": "/posters/previews/10_things_0_talent_respect_final_24x36_3600x5400.webp",
  "/posters/poster_01_blue_grunge_10_things_24x36_3600x5400.png": "/posters/previews/poster_01_blue_grunge_10_things_24x36_3600x5400.webp",
  "/posters/10_things_zero_talent_24x36_3600x5400.png": "/posters/previews/10_things_zero_talent_24x36_3600x5400.webp",
  "/posters/name_the_claim_24x36_3600x5400.png": "/posters/previews/name_the_claim_24x36_3600x5400.webp",
  "/posters/find_the_flaw_24x36_3600x5400.png": "/posters/previews/find_the_flaw_24x36_3600x5400.webp",
  "/posters/nietzsche_why_poster_24x36_3600x5400.png": "/posters/previews/nietzsche_why_poster_24x36_3600x5400.webp",
  "/posters/frankl_choose_attitude_24x36_3600x5400.png": "/posters/previews/frankl_choose_attitude_24x36_3600x5400.webp",
  "/posters/douglass_struggle_progress_24x36_3600x5400.png": "/posters/previews/douglass_struggle_progress_24x36_3600x5400.webp",
  "/posters/camus_invincible_summer_FINAL_3600x5400.png": "/posters/previews/camus_invincible_summer_final_3600x5400.webp",
  "/posters/eliot_be_still_FINAL_3600x5400.png": "/posters/previews/eliot_be_still_final_3600x5400.webp",
  "/posters/marie_curie_understand_more_fear_less_24x36_3600x5400.png": "/posters/previews/marie_curie_understand_more_fear_less_24x36_3600x5400.webp",
  "/posters/antoine_de_saint_exupery_perfection_24x36_3600x5400.png": "/posters/previews/antoine_de_saint_exupery_perfection_24x36_3600x5400.webp",
  "/posters/aqr_nothing_will_work_unless_you_do_24x36_3600x5400.png": "/posters/previews/aqr_nothing_will_work_unless_you_do_24x36_3600x5400.webp",
  "/posters/before_you_24x36_3600x5400.png": "/posters/previews/before_you_24x36_3600x5400.webp",
  "/posters/before_you_speak_three_gates_24x36_3600x5400.png": "/posters/previews/before_you_speak_three_gates_24x36_3600x5400.webp",
  "/posters/watch_your_thoughts_24x36_3600x5400.png": "/posters/previews/watch_your_thoughts_24x36_3600x5400.webp",
};

// Returns the web preview for a master png, or the master itself if no preview exists.
export function posterPreview(png: string): string {
  return POSTER_PREVIEWS[png] ?? png;
}
