import type { VocabularyTerm } from "./vocabularyData";
export const q4Terms: VocabularyTerm[] = [
  {
    term: "Cherry-picking",
    group: "Quarter-essential",
    fullDefinition: "Cherry-picking is selecting only the data, dates, groups, examples, or evidence that support a preferred story while ignoring relevant information that challenges it.",
    plainLanguage: "Showing only the pieces that help one side.",
    aqrUse: "You will look for missing time periods, comparison groups, and counterevidence before accepting a conclusion.",
    questionStem: "The presentation may be cherry-picking ______.",
  },
  {
    term: "Comparison",
    group: "Quarter-essential",
    fullDefinition: "A comparison examines similarities, differences, ratios, changes, or relative size between quantities, groups, time periods, or conditions.",
    plainLanguage: "Looking at one thing in relation to another.",
    aqrUse: "AQR asks 'Compared to what?' because a number often has little meaning without a fair reference point.",
    questionStem: "The claim is comparing ______ with ______.",
  },
  {
    term: "Context",
    group: "Quarter-essential",
    fullDefinition: "Context is the background information, conditions, definitions, time period, comparison, and situation needed to understand a number, statement, or event accurately.",
    plainLanguage: "The surrounding information needed to understand something correctly.",
    aqrUse: "You will look for missing context that changes what a graph, statistic, quote, or claim means.",
    questionStem: "The missing context is ______.",
  },
  {
    term: "Counterevidence",
    group: "Quarter-essential",
    fullDefinition: "Counterevidence is relevant information that challenges, weakens, complicates, or contradicts a claim or explanation.",
    plainLanguage: "Evidence that points against the claim or shows the story is incomplete.",
    aqrUse: "Strong thinkers actively search for counterevidence and revise when the evidence changes the balance.",
    questionStem: "One piece of counterevidence is ______.",
  },
  {
    term: "Credibility",
    group: "Quarter-essential",
    fullDefinition: "Credibility is the degree to which a source, author, method, or claim deserves trust based on expertise, evidence, transparency, accuracy, and possible incentives or conflicts.",
    plainLanguage: "How much a source deserves to be trusted.",
    aqrUse: "You will evaluate credibility with reasons instead of using reputation alone or assuming a professional-looking page is reliable.",
    questionStem: "This source is more or less credible because ______.",
  },
  {
    term: "Denominator",
    group: "Quarter-essential",
    fullDefinition: "The denominator is the bottom number in a fraction and represents the whole, total, or reference amount used in a ratio, rate, or percentage.",
    plainLanguage: "The whole or base that the part is being compared with.",
    aqrUse: "You will ask for the denominator when percentages or rates are used to create a dramatic impression.",
    questionStem: "The denominator is ______, which matters because ______.",
  },
  {
    term: "Method",
    group: "Quarter-essential",
    fullDefinition: "A method is the process used to collect, select, measure, calculate, analyze, or present information. Different methods can produce different results.",
    plainLanguage: "How the information was gathered or worked with.",
    aqrUse: "You will examine whether the method fits the question and whether it introduces bias or important limitations.",
    questionStem: "The method may affect the result because ______.",
  },
  {
    term: "Misleading display",
    group: "Quarter-essential",
    fullDefinition: "A misleading display is a graph, chart, table, image, or visual design that creates an inaccurate, exaggerated, incomplete, or unfair impression even if some numbers are technically correct.",
    plainLanguage: "A visual that pushes you toward the wrong impression.",
    aqrUse: "You will identify scale tricks, missing labels, unequal intervals, distorted images, and unfair comparisons.",
    questionStem: "This display is misleading because ______.",
  },
  {
    term: "Reasonable belief",
    group: "Quarter-essential",
    fullDefinition: "A reasonable belief is a conclusion that fits the best available evidence while acknowledging uncertainty, alternatives, and limitations. It may change when stronger evidence appears.",
    plainLanguage: "What it makes sense to believe right now, based on the evidence.",
    aqrUse: "Q4 ends with careful judgments, not demands for perfect certainty or automatic disbelief.",
    questionStem: "A reasonable person should currently believe ______, while still questioning ______.",
  },
  {
    term: "Source",
    group: "Quarter-essential",
    fullDefinition: "A source is the person, organization, document, dataset, publication, website, or system from which information or evidence comes.",
    plainLanguage: "Where the information came from.",
    aqrUse: "You will trace claims and numbers back to their original or best available source instead of trusting screenshots or repeated posts.",
    questionStem: "The original source is ______.",
  },
  {
    term: "Anecdote",
    group: "Recognize and begin using",
    fullDefinition: "An anecdote is a brief story or personal example about a single event or person. Anecdotes may illustrate an issue but usually cannot establish how common something is.",
    plainLanguage: "One person's story or example.",
    aqrUse: "You will distinguish meaningful personal experience from evidence strong enough to support a broad claim.",
    questionStem: "This anecdote does not prove ______.",
  },
  {
    term: "Base rate",
    group: "Recognize and begin using",
    fullDefinition: "A base rate is the normal or background frequency of an event in a population before new evidence or a special test result is considered.",
    plainLanguage: "How common something usually is before looking at the new case.",
    aqrUse: "Base rates help prevent dramatic examples or test results from being interpreted without the larger pattern.",
    questionStem: "The base rate matters because ______.",
  },
  {
    term: "Conflict of interest",
    group: "Recognize and begin using",
    fullDefinition: "A conflict of interest exists when a personal, financial, professional, or organizational interest could influence judgment, research, reporting, or recommendations.",
    plainLanguage: "A reason someone may benefit from one conclusion or choice.",
    aqrUse: "You will consider incentives without assuming that a conflict automatically proves dishonesty or error.",
    questionStem: "A possible conflict of interest is ______.",
  },
  {
    term: "False precision",
    group: "Recognize and begin using",
    fullDefinition: "False precision occurs when numbers are reported with more exact digits or certainty than the measurement, data, or method can reasonably support.",
    plainLanguage: "Making a number look more exact than the evidence allows.",
    aqrUse: "You will question outputs such as 87.463 percent when the inputs are rough estimates or small samples.",
    questionStem: "This number shows false precision because ______.",
  },
  {
    term: "Generalization",
    group: "Recognize and begin using",
    fullDefinition: "A generalization is a broad statement extended from particular examples, observations, or samples to a larger group or situation.",
    plainLanguage: "A broad conclusion based on a smaller set of cases.",
    aqrUse: "You will decide whether the evidence supports the size of the generalization being made.",
    questionStem: "This generalization goes beyond the evidence because ______.",
  },
  {
    term: "Transparency",
    group: "Recognize and begin using",
    fullDefinition: "Transparency is openness about sources, data, methods, calculations, funding, assumptions, uncertainty, and limitations so others can examine the work.",
    plainLanguage: "Showing where the information came from and how the conclusion was made.",
    aqrUse: "You will value explanations that make their process visible and be cautious when key details are hidden.",
    questionStem: "The analysis would be more transparent if ______.",
  },
  {
    term: "Burden of proof",
    group: "Extension vocabulary",
    fullDefinition: "Burden of proof is the responsibility to provide sufficient evidence for a claim, especially when the claim is strong, surprising, or consequential.",
    plainLanguage: "The person making the claim has to support it.",
    aqrUse: "You will match the strength of the evidence required to the size and importance of the claim.",
    questionStem: "The burden of proof is higher here because ______.",
  },
  {
    term: "Framing",
    group: "Extension vocabulary",
    fullDefinition: "Framing is the way information is selected, organized, worded, or presented so that an audience is encouraged to view an issue from a particular perspective.",
    plainLanguage: "How a story is shaped to influence how people see it.",
    aqrUse: "You will compare different ways the same data can be framed and identify which details are emphasized or hidden.",
    questionStem: "This claim is framed to make the audience focus on ______.",
  },
  {
    term: "Provenance",
    group: "Extension vocabulary",
    fullDefinition: "Provenance is the documented origin, history, ownership, and movement of data, information, or an artifact.",
    plainLanguage: "The traceable story of where information came from.",
    aqrUse: "Checking provenance helps you find the original dataset, identify changes, and avoid relying on detached screenshots.",
    questionStem: "The provenance of this number can be traced to ______.",
  },
  {
    term: "Statistical significance",
    group: "Extension vocabulary",
    fullDefinition: "Statistical significance is a formal judgment that an observed result would be unlikely under a stated chance model, given particular assumptions. It does not automatically show that a result is important, large, or causal.",
    plainLanguage: "A test suggests the result may not be due only to chance.",
    aqrUse: "Extension learners may distinguish statistical significance from practical importance and causation.",
    questionStem: "Even if the result is statistically significant, we still need to ask ______.",
  },
  {
    term: "Survivorship bias",
    group: "Extension vocabulary",
    fullDefinition: "Survivorship bias occurs when conclusions are based mainly on the people, cases, or examples that remained visible or successful while failures and missing cases are ignored.",
    plainLanguage: "Looking only at what survived and forgetting what disappeared.",
    aqrUse: "You will ask whether success stories leave out the larger number of attempts that failed or were never reported.",
    questionStem: "Survivorship bias may be present because ______ is missing.",
  },
  {
    term: "Triangulation",
    group: "Extension vocabulary",
    fullDefinition: "Triangulation is checking a question or conclusion by using multiple sources, methods, datasets, or perspectives and comparing whether they point toward a similar result.",
    plainLanguage: "Checking the same idea in more than one independent way.",
    aqrUse: "You may triangulate a claim with an original source, another credible source, and your own calculation.",
    questionStem: "I triangulated the claim by comparing ______, ______, and ______.",
  },
];
