import type { VocabularyTerm } from "./vocabularyData";

export const q1Terms: VocabularyTerm[] = [
  {
    term: "Ability",
    group: "Quarter-essential",
    fullDefinition: "Ability is the current capacity to perform a task or demonstrate a skill. Ability can develop with instruction, practice, tools, support, and experience.",
    plainLanguage: "What you can currently show that you can do.",
    aqrUse: "Q1 asks for evidence of current ability without turning one score or struggle into a permanent label.",
    questionStem: "The evidence of my current ability is ______.",
  },
  {
    term: "Comprehension",
    group: "Quarter-essential",
    fullDefinition: "Comprehension is understanding the meaning, relationships, implications, and important details of information. It is more than recognizing words or repeating an answer.",
    plainLanguage: "Actually understanding what something means.",
    aqrUse: "Your learning agent should check comprehension instead of only giving answers or summaries.",
    questionStem: "To show comprehension, I can explain ______ in my own words.",
  },
  {
    term: "Confidence",
    group: "Quarter-essential",
    fullDefinition: "Confidence is the degree to which a person feels sure about an answer, skill, decision, or ability. Confidence may be higher or lower than actual accuracy or performance.",
    plainLanguage: "How sure or capable you feel.",
    aqrUse: "You will compare confidence with evidence and learn that confident AI output can still be wrong.",
    questionStem: "My confidence is ______ because ______.",
  },
  {
    term: "Habit",
    group: "Quarter-essential",
    fullDefinition: "A habit is a behavior or response repeated often enough to become a regular pattern. Habits can support or interfere with goals, and they can change over time.",
    plainLanguage: "Something you do regularly, often without much thought.",
    aqrUse: "You will identify habits that affect school, work, attention, organization, and follow-through.",
    questionStem: "One habit affecting my work is ______",
  },
  {
    term: "Measurement",
    group: "Quarter-essential",
    fullDefinition: "Measurement is the process of assigning a number, category, rating, or description to an attribute according to a stated method or scale. Good measurement requires clarity about what is being measured and how.",
    plainLanguage: "A way of describing something with a number, category, or rating.",
    aqrUse: "In Q1, you will question what surveys, ratings, diagnostics, and self-reports actually measure.",
    questionStem: "What exactly is being measured here?",
  },
  {
    term: "Preference",
    group: "Quarter-essential",
    fullDefinition: "A preference is a tendency to favor, enjoy, or choose one option, method, environment, or style over another. A preference does not necessarily show what produces the best result.",
    plainLanguage: "What you tend to like or choose.",
    aqrUse: "You will distinguish preferred ways of learning from demonstrated ability and from supports that actually help.",
    questionStem: "My preference is ______, but that does not prove ______.",
  },
  {
    term: "Quantity",
    group: "Quarter-essential",
    fullDefinition: "A quantity is an amount, size, count, duration, rate, or other feature that can be measured or represented with a number and, when appropriate, a unit.",
    plainLanguage: "An amount that can be counted or measured.",
    aqrUse: "You will identify the real quantity behind a number instead of treating every number as self-explanatory.",
    questionStem: "What quantity does this number represent?",
  },
  {
    term: "Rating",
    group: "Quarter-essential",
    fullDefinition: "A rating is a value assigned to represent a judgment, level, quality, frequency, or self-report. Ratings are useful but may depend on the person, wording, mood, and meaning of the scale.",
    plainLanguage: "A score that represents someone's judgment or level.",
    aqrUse: "Learner-profile ratings help you reflect, but they do not automatically prove ability or permanent traits.",
    questionStem: "Is this rating measuring skill, confidence, preference, or something else?",
  },
  {
    term: "Scale",
    group: "Quarter-essential",
    fullDefinition: "A scale is an ordered system used to assign, compare, or display values. A scale may be numerical, such as 1 to 5, or visual, such as the range shown on a graph axis.",
    plainLanguage: "The system or range used to show how much.",
    aqrUse: "You will examine what points on a rating scale mean and how changing a graph scale can change the impression it creates.",
    questionStem: "What does each point on this scale mean?",
  },
  {
    term: "Unit",
    group: "Quarter-essential",
    fullDefinition: "A unit is an agreed-upon standard used to describe the size or amount of a quantity, such as minutes, dollars, miles, points, or responses. A number without its unit may be incomplete or misleading.",
    plainLanguage: "The label that tells what a number is measuring.",
    aqrUse: "AQR repeatedly asks you to include units and check whether comparisons use compatible units.",
    questionStem: "The unit is ______, and it matters because ______.",
  },
  {
    term: "Diagnostic",
    group: "Recognize and begin using",
    fullDefinition: "A diagnostic is a check used to identify a starting point, strength, need, misconception, or area for further investigation. A diagnostic is intended to guide support, not permanently label a person.",
    plainLanguage: "A starting-point check that helps find what support may be needed.",
    aqrUse: "Q1 diagnostics should feed the learner profile or learning-agent instructions instead of becoming random tests.",
    questionStem: "This diagnostic is intended to measure ______.",
  },
  {
    term: "Feedback",
    group: "Recognize and begin using",
    fullDefinition: "Feedback is information about performance, understanding, design, or progress that can guide improvement. Useful feedback is specific, relevant, understandable, and connected to a next step.",
    plainLanguage: "Information that helps you improve.",
    aqrUse: "You will use feedback to revise profiles, prompts, tools, explanations, and project products.",
    questionStem: "The feedback led me to change ______.",
  },
  {
    term: "Inventory",
    group: "Recognize and begin using",
    fullDefinition: "An inventory is an organized list or set of questions used to collect information about experiences, habits, interests, skills, resources, or needs.",
    plainLanguage: "A structured set of questions that collects information about you or a situation.",
    aqrUse: "Interest, habit, and support inventories become source material that you interpret rather than accept blindly.",
    questionStem: "The inventory identified ______.",
  },
  {
    term: "Profile",
    group: "Recognize and begin using",
    fullDefinition: "A profile is an organized description created from multiple pieces of information about a person, group, object, or situation. A useful profile is selective, evidence-based, and open to revision.",
    plainLanguage: "A structured picture built from several kinds of information.",
    aqrUse: "Your learner profile combines interests, strengths, challenges, preferences, goals, and support needs for use in future tools.",
    questionStem: "My learner profile shows ______.",
  },
  {
    term: "Prompt",
    group: "Recognize and begin using",
    fullDefinition: "A prompt is the instruction, question, context, or task given to a person or AI system to guide a response. Effective prompts state the job, needed information, limits, and desired output.",
    plainLanguage: "The directions or question you give to a person or AI tool.",
    aqrUse: "You will write prompts that use your learner profile and ask for help without outsourcing your thinking.",
    questionStem: "I improved the prompt by adding ______.",
  },
  {
    term: "Self-data",
    group: "Recognize and begin using",
    fullDefinition: "Self-data are information a person records, reports, or measures about themselves, such as time use, sleep, confidence ratings, habits, interests, or task completion.",
    plainLanguage: "Information you collect or report about yourself.",
    aqrUse: "Your learner profile uses self-data, but you will also discuss its limits, including memory, honesty, mood, and measurement quality.",
    questionStem: "This self-data suggests ______, but it does not prove ______.",
  },
  {
    term: "Verify",
    group: "Recognize and begin using",
    fullDefinition: "To verify means to check whether information, a result, or an output is accurate, supported, consistent, or traceable by comparing it with evidence, calculation, a source, or another method.",
    plainLanguage: "Check that something is actually correct or supported.",
    aqrUse: "You are responsible for checking AI output, calculations, sources, and claims before using them.",
    questionStem: "I verified this by ______.",
  },
  {
    term: "Cognitive load",
    group: "Extension vocabulary",
    fullDefinition: "Cognitive load is the amount of mental effort being used in working memory while a person is trying to understand or complete a task.",
    plainLanguage: "How much your brain is trying to hold and process at once.",
    aqrUse: "You may identify when directions, vocabulary, or tool steps create unnecessary overload and redesign the support.",
    questionStem: "The cognitive load could be reduced by ______.",
  },
  {
    term: "Metacognition",
    group: "Extension vocabulary",
    fullDefinition: "Metacognition is awareness and management of one's own thinking, understanding, strategies, errors, and learning processes.",
    plainLanguage: "Thinking about how you think and learn.",
    aqrUse: "A stronger learner can explain which strategy worked, where confusion began, and what to change next.",
    questionStem: "My metacognition improved when I noticed ______.",
  },
  {
    term: "Operational definition",
    group: "Extension vocabulary",
    fullDefinition: "An operational definition states exactly how an idea or variable will be observed, measured, counted, or classified in a particular study or project.",
    plainLanguage: "A precise rule for what a term means in the actual measurement.",
    aqrUse: "Operational definitions prevent vague ideas such as focus, success, or stress from being measured differently by each person.",
    questionStem: "In this project, we will define ______ as ______.",
  },
  {
    term: "Proxy measure",
    group: "Extension vocabulary",
    fullDefinition: "A proxy measure is an indirect variable used to represent a harder-to-measure idea because the idea itself cannot be measured directly or easily.",
    plainLanguage: "A substitute measurement used for something difficult to measure.",
    aqrUse: "You may use assignment completion as a proxy for productivity while explaining why the two are not identical.",
    questionStem: "We are using ______ as a proxy for ______.",
  },
  {
    term: "Self-efficacy",
    group: "Extension vocabulary",
    fullDefinition: "Self-efficacy is a person's belief that they can organize and carry out the actions needed to succeed at a particular task or goal.",
    plainLanguage: "Your belief that you can handle a specific task.",
    aqrUse: "Extension learners may distinguish self-efficacy from general confidence and examine how evidence, practice, and support change it.",
    questionStem: "My self-efficacy for ______ changed when ______.",
  },
  {
    term: "Validity",
    group: "Extension vocabulary",
    fullDefinition: "Validity is the degree to which a measure, method, model, or conclusion actually represents or answers what it claims to represent or answer.",
    plainLanguage: "Whether you are really measuring the thing you say you are measuring.",
    aqrUse: "A learner survey can be consistent but still invalid if its questions do not match the ability or trait it claims to measure.",
    questionStem: "The validity is questionable because ______.",
  },
];
