import type { VocabularyTerm } from "./vocabularyData";
export const q3Terms: VocabularyTerm[] = [
  {
    term: "Decision rule",
    group: "Quarter-essential",
    fullDefinition: "A decision rule is an explicit procedure that uses inputs, criteria, conditions, scores, or thresholds to produce a result or recommendation.",
    plainLanguage: "The rule the tool follows to turn information into an answer.",
    aqrUse: "Your tool must show its logic so another person can understand and test how the recommendation was produced.",
    questionStem: "The decision rule says that if ______, then ______.",
  },
  {
    term: "Failure case",
    group: "Quarter-essential",
    fullDefinition: "A failure case is a situation in which a model or tool produces an unreasonable, harmful, incorrect, confusing, or unusable result.",
    plainLanguage: "A situation where the tool breaks down or gives bad advice.",
    aqrUse: "You will deliberately look for cases that expose weak logic so you can revise before final use.",
    questionStem: "One failure case occurs when ______.",
  },
  {
    term: "Opportunity cost",
    group: "Quarter-essential",
    fullDefinition: "Opportunity cost is the value of the best alternative not chosen when a decision is made. It focuses on what could have been gained from the next-best option.",
    plainLanguage: "What you miss out on by choosing something else.",
    aqrUse: "You will identify the most important alternative being given up, not list every possible loss.",
    questionStem: "The opportunity cost of this choice is ______.",
  },
  {
    term: "Option",
    group: "Quarter-essential",
    fullDefinition: "An option is one possible choice, action, product, plan, route, or response being considered in a decision. Options should be clear enough to compare using the same criteria.",
    plainLanguage: "One of the choices you could make.",
    aqrUse: "Your decision tool needs a defined set of realistic options rather than a vague question with no comparable choices.",
    questionStem: "The options being compared are ______.",
  },
  {
    term: "Priority",
    group: "Quarter-essential",
    fullDefinition: "A priority is a goal, need, value, or criterion judged to be more important than competing considerations.",
    plainLanguage: "Something that matters more than other things in the decision.",
    aqrUse: "A user's priorities help determine criteria, weights, and acceptable trade-offs.",
    questionStem: "My highest priority is ______.",
  },
  {
    term: "Sensitivity",
    group: "Quarter-essential",
    fullDefinition: "Sensitivity describes how much a model's output or recommendation changes when an input, weight, criterion, or assumption changes.",
    plainLanguage: "How easily the answer changes when one part changes.",
    aqrUse: "You will change one reasonable input at a time to see whether the recommendation is stable or fragile.",
    questionStem: "The recommendation is sensitive to ______.",
  },
  {
    term: "Validation",
    group: "Quarter-essential",
    fullDefinition: "Validation is the process of checking whether a model, tool, method, or result works reasonably for its intended purpose and users. Validation may involve examples, known cases, user tests, or comparison with evidence.",
    plainLanguage: "Checking whether the tool works the way it is supposed to.",
    aqrUse: "AQR validation means more than clicking buttons; it means testing whether outputs make sense for real situations.",
    questionStem: "We validated the tool by ______.",
  },
  {
    term: "Weight",
    group: "Quarter-essential",
    fullDefinition: "A weight is a value assigned to show how much influence a criterion has in a score, model, or decision rule. Larger weights give that criterion more effect on the result.",
    plainLanguage: "A number showing how important a criterion is in the model.",
    aqrUse: "You will explain weights as value choices, not pretend they are automatically objective.",
    questionStem: "This criterion receives more weight because ______.",
  },
  {
    term: "Conditional",
    group: "Recognize and begin using",
    fullDefinition: "A statement or recommendation is conditional when it depends on another condition, input, or event being true.",
    plainLanguage: "It is true or recommended only if something else is true.",
    aqrUse: "Many good recommendations should be conditional because the best choice changes with the user or situation.",
    questionStem: "This recommendation is conditional on ______.",
  },
  {
    term: "Expected value",
    group: "Recognize and begin using",
    fullDefinition: "Expected value is the probability-weighted average outcome of a repeated uncertain situation. It combines possible outcomes with their chances, but it does not guarantee what will happen once.",
    plainLanguage: "The long-run average outcome when chances and results are combined.",
    aqrUse: "Expected value may help compare risky options when probability information is available and meaningful.",
    questionStem: "The expected value helps compare ______.",
  },
  {
    term: "Prototype",
    group: "Recognize and begin using",
    fullDefinition: "A prototype is an early working version of a product, model, or tool created for testing, feedback, and revision before final use.",
    plainLanguage: "A first working version built to learn from.",
    aqrUse: "Your prototype is expected to be incomplete; its job is to reveal what needs to be improved.",
    questionStem: "The prototype revealed that ______.",
  },
  {
    term: "Reliability",
    group: "Recognize and begin using",
    fullDefinition: "Reliability is the degree to which a tool, measure, process, or source produces consistent and dependable results under similar conditions.",
    plainLanguage: "How consistently something works or gives similar results.",
    aqrUse: "You will examine whether the same inputs produce stable outputs and whether the tool behaves dependably across tests.",
    questionStem: "The tool's reliability is limited by ______.",
  },
  {
    term: "Scenario",
    group: "Recognize and begin using",
    fullDefinition: "A scenario is a possible set of conditions used to imagine, compare, or test what may happen in a situation.",
    plainLanguage: "A possible version of the situation.",
    aqrUse: "You will test tools under ordinary, difficult, and unusual scenarios instead of checking only one easy example.",
    questionStem: "Under this scenario, ______.",
  },
  {
    term: "Score",
    group: "Recognize and begin using",
    fullDefinition: "A score is a numerical result used to summarize performance, fit, or value across one or more criteria. A score depends on the rules used to create it.",
    plainLanguage: "A number the model uses to summarize how an option did.",
    aqrUse: "You will explain what a score represents and avoid treating it as truth without examining the formula behind it.",
    questionStem: "This option received a score of ______ because ______.",
  },
  {
    term: "Threshold",
    group: "Recognize and begin using",
    fullDefinition: "A threshold is a cutoff value or condition at which a category, output, decision, or action changes.",
    plainLanguage: "A cutoff point that changes what happens next.",
    aqrUse: "Decision tools may use thresholds, but you should test whether the cutoff is reasonable and what happens near it.",
    questionStem: "If the value crosses the threshold of ______, then ______.",
  },
  {
    term: "Calibration",
    group: "Extension vocabulary",
    fullDefinition: "Calibration is the process of adjusting a model, measure, or tool so its outputs better match known evidence, expected behavior, or real results.",
    plainLanguage: "Tuning a tool so its results better match reality.",
    aqrUse: "You may calibrate weights, thresholds, or scoring rules after testing reveals that the tool consistently overstates or understates something.",
    questionStem: "We calibrated the model by changing ______ after noticing ______.",
  },
  {
    term: "Multi-criteria analysis",
    group: "Extension vocabulary",
    fullDefinition: "Multi-criteria analysis is a structured method for comparing options using several criteria that may differ in importance or measurement.",
    plainLanguage: "Comparing choices across several things that matter.",
    aqrUse: "A stronger decision tool may combine criteria, weights, scores, and trade-offs while keeping the logic visible.",
    questionStem: "The multi-criteria analysis favors ______ because ______.",
  },
  {
    term: "Normalization",
    group: "Extension vocabulary",
    fullDefinition: "Normalization is the process of converting values measured on different scales into a common form so they can be compared or combined more fairly.",
    plainLanguage: "Putting different kinds of scores onto a shared scale.",
    aqrUse: "Extension learners may normalize cost, distance, ratings, or other variables before combining them in a model.",
    questionStem: "We normalized ______ so it could be compared with ______.",
  },
  {
    term: "Optimization",
    group: "Extension vocabulary",
    fullDefinition: "Optimization is the process of finding the best available solution under stated goals, criteria, and constraints.",
    plainLanguage: "Finding the best choice that still fits the limits.",
    aqrUse: "Extension learners may improve a decision rule by identifying what is being maximized or minimized and which constraints must remain satisfied.",
    questionStem: "This model is trying to optimize ______ while respecting ______.",
  },
  {
    term: "Robustness",
    group: "Extension vocabulary",
    fullDefinition: "Robustness is the degree to which a model, method, or conclusion remains useful and stable when reasonable assumptions, inputs, or conditions change.",
    plainLanguage: "How well the result holds up when things change a little.",
    aqrUse: "A robust recommendation survives several reasonable sensitivity tests instead of collapsing after one small change.",
    questionStem: "The model is robust because ______.",
  },
  {
    term: "Utility",
    group: "Extension vocabulary",
    fullDefinition: "Utility is the usefulness, satisfaction, or value that an outcome or option has for a particular person or purpose. Utility may differ across users even when measurable costs are the same.",
    plainLanguage: "How useful or valuable an outcome is to the person making the decision.",
    aqrUse: "Decision tools can represent different users' values while making those value choices visible.",
    questionStem: "This option has greater utility for this user because ______.",
  },
];
