import type { VocabularyTerm } from "./vocabularyData";
export const q2Terms: VocabularyTerm[] = [
  {
    term: "Bias",
    group: "Quarter-essential",
    fullDefinition: "Bias is a systematic influence that pushes data collection, measurement, selection, analysis, or interpretation in a particular direction. Bias can be intentional or unintentional.",
    plainLanguage: "Something in the process that unfairly tilts the result.",
    aqrUse: "You will look for bias in survey wording, who responds, what gets measured, and how results are displayed.",
    questionStem: "A possible source of bias is ______.",
  },
  {
    term: "Causation",
    group: "Quarter-essential",
    fullDefinition: "Causation is a relationship in which a change in one factor produces a change in another. Establishing causation usually requires stronger evidence and design than simply observing a correlation.",
    plainLanguage: "One thing actually helps cause the other to change.",
    aqrUse: "You will ask what kind of study or evidence would be needed before claiming that one variable caused another.",
    questionStem: "This does not establish causation because ______.",
  },
  {
    term: "Correlation",
    group: "Quarter-essential",
    fullDefinition: "Correlation is a statistical relationship in which two variables tend to vary together. Correlation describes association, not proof that one variable causes the other.",
    plainLanguage: "Two things tend to change together.",
    aqrUse: "You will identify correlations in student and media data while resisting causal language that the evidence cannot support.",
    questionStem: "The data show a correlation between ______ and ______.",
  },
  {
    term: "Dataset",
    group: "Quarter-essential",
    fullDefinition: "A dataset is an organized collection of related data, usually arranged so observations and variables can be identified, compared, summarized, and analyzed.",
    plainLanguage: "A group of related data kept together for analysis.",
    aqrUse: "In Q2, you will build or use a manageable dataset and keep its structure clear enough to make honest claims.",
    questionStem: "This dataset contains ______.",
  },
  {
    term: "Distribution",
    group: "Quarter-essential",
    fullDefinition: "A distribution describes how the values of a variable are spread across possible values or categories, including where values cluster, how much they vary, and whether unusual values appear.",
    plainLanguage: "The overall shape and spread of the data.",
    aqrUse: "You will describe more than one average by noticing clusters, gaps, spread, and unusual values.",
    questionStem: "The distribution shows ______.",
  },
  {
    term: "Leading question",
    group: "Quarter-essential",
    fullDefinition: "A leading question is worded in a way that encourages, suggests, or pressures a particular response instead of allowing a neutral answer.",
    plainLanguage: "A question that nudges people toward one answer.",
    aqrUse: "Before collecting survey data, you will revise questions that contain assumptions, emotional wording, or a preferred answer.",
    questionStem: "This question is leading because ______.",
  },
  {
    term: "Observation",
    group: "Quarter-essential",
    fullDefinition: "An observation is one recorded case, person, event, object, time period, or response in a dataset. In a table, an observation is often represented by one row.",
    plainLanguage: "One case or recorded item in the data.",
    aqrUse: "You will identify what each row or entry represents before making graphs or summaries.",
    questionStem: "Each observation represents ______.",
  },
  {
    term: "Outlier",
    group: "Quarter-essential",
    fullDefinition: "An outlier is an observation or value that lies noticeably far from most other values in a dataset. Outliers may be errors, unusual cases, or important information.",
    plainLanguage: "A value that is far away from most of the others.",
    aqrUse: "You will investigate outliers instead of automatically deleting them or letting them silently distort a summary.",
    questionStem: "This outlier may affect ______.",
  },
  {
    term: "Pattern",
    group: "Quarter-essential",
    fullDefinition: "A pattern is a noticeable regularity, trend, difference, repetition, or relationship in data. A pattern may be meaningful, accidental, weak, or caused by another factor.",
    plainLanguage: "Something in the data that happens in a noticeable way.",
    aqrUse: "You will describe patterns carefully before deciding what they mean or whether they support a claim.",
    questionStem: "A pattern I notice is ______.",
  },
  {
    term: "Population",
    group: "Quarter-essential",
    fullDefinition: "A population is the complete group of people, objects, events, or cases that a question or conclusion is intended to describe.",
    plainLanguage: "The whole group you want to understand.",
    aqrUse: "You will name the population before deciding whether your sample can reasonably speak for it.",
    questionStem: "The population we want to understand is ______.",
  },
  {
    term: "Representative",
    group: "Quarter-essential",
    fullDefinition: "A sample is representative when it reflects the larger population in the characteristics that matter for the question. A representative sample reduces, but does not remove, uncertainty.",
    plainLanguage: "Similar enough to the larger group to support a fair conclusion.",
    aqrUse: "You will decide whether the sample gives a balanced picture or leaves important groups out.",
    questionStem: "This sample may not be representative because ______.",
  },
  {
    term: "Sample",
    group: "Quarter-essential",
    fullDefinition: "A sample is the smaller group of people, objects, events, or cases actually measured, surveyed, or observed in order to learn about a larger population.",
    plainLanguage: "The part of the whole group that you actually collected data from.",
    aqrUse: "You will compare your sample with the population and state who was included or missing.",
    questionStem: "Our sample includes ______.",
  },
  {
    term: "Categorical data",
    group: "Recognize and begin using",
    fullDefinition: "Categorical data place observations into names, labels, or groups, such as grade level, transportation type, or preferred study location.",
    plainLanguage: "Data that sort things into groups or labels.",
    aqrUse: "You will count, compare, and display categories without treating their labels as quantities.",
    questionStem: "This variable is categorical because ______.",
  },
  {
    term: "Confounding variable",
    group: "Recognize and begin using",
    fullDefinition: "A confounding variable is another factor related to the variables being studied that could partly or fully explain an observed relationship.",
    plainLanguage: "Another factor that could explain why two things seem connected.",
    aqrUse: "When you see a correlation, you will name plausible confounding variables before suggesting causation.",
    questionStem: "A possible confounding variable is ______.",
  },
  {
    term: "Frequency",
    group: "Recognize and begin using",
    fullDefinition: "Frequency is the number of times a value, category, or event occurs in a dataset.",
    plainLanguage: "How often something happens or appears.",
    aqrUse: "Frequencies help you build tables and graphs and compare common and uncommon responses.",
    questionStem: "The most frequent response was ______.",
  },
  {
    term: "Mean",
    group: "Recognize and begin using",
    fullDefinition: "The mean is the sum of all numerical values divided by the number of values. It uses every value and can be strongly affected by extreme values.",
    plainLanguage: "The arithmetic average.",
    aqrUse: "You will decide whether the mean gives a useful summary or whether outliers make it misleading.",
    questionStem: "The mean may be affected by ______.",
  },
  {
    term: "Median",
    group: "Recognize and begin using",
    fullDefinition: "The median is the middle value when numerical data are ordered. If there are two middle values, the median is their mean.",
    plainLanguage: "The middle value in an ordered list.",
    aqrUse: "You will compare the median with the mean when data are skewed or contain outliers.",
    questionStem: "The median may better represent ______ because ______.",
  },
  {
    term: "Numerical data",
    group: "Recognize and begin using",
    fullDefinition: "Numerical data are values recorded as numbers for which arithmetic operations or meaningful quantitative comparisons can be made, such as time, distance, count, or rating.",
    plainLanguage: "Data recorded as meaningful numbers.",
    aqrUse: "You will choose appropriate summaries and graphs based partly on whether a variable is numerical.",
    questionStem: "This variable is numerical because ______.",
  },
  {
    term: "Proportion",
    group: "Recognize and begin using",
    fullDefinition: "A proportion compares a part with the whole and may be written as a fraction, decimal, or percentage. The denominator must be clear.",
    plainLanguage: "How much of the whole belongs to one part.",
    aqrUse: "You will use proportions to compare groups of different sizes more fairly than raw counts sometimes allow.",
    questionStem: "The proportion of ______ was ______.",
  },
  {
    term: "Response rate",
    group: "Recognize and begin using",
    fullDefinition: "Response rate is the proportion or percentage of invited or eligible participants who actually complete a survey or provide usable responses.",
    plainLanguage: "How many of the people asked actually responded.",
    aqrUse: "A low response rate may create bias if responders differ from people who did not respond.",
    questionStem: "The response rate matters because ______.",
  },
  {
    term: "Effect size",
    group: "Extension vocabulary",
    fullDefinition: "Effect size is a measure of how large or meaningful a difference, relationship, or change is, rather than only whether it exists.",
    plainLanguage: "How big the difference or relationship actually is.",
    aqrUse: "Extension learners may distinguish a tiny detectable pattern from a difference large enough to matter in real life.",
    questionStem: "The effect size matters because ______.",
  },
  {
    term: "Generalizability",
    group: "Extension vocabulary",
    fullDefinition: "Generalizability is the degree to which findings from a sample, setting, or study can reasonably apply to other people, places, times, or situations.",
    plainLanguage: "How far the result can fairly be extended beyond the original group.",
    aqrUse: "You will connect generalizability to sample quality, context, measurement, and method.",
    questionStem: "These results may not generalize to ______ because ______.",
  },
  {
    term: "Interquartile range",
    group: "Extension vocabulary",
    fullDefinition: "The interquartile range, or IQR, is the distance between the first and third quartiles and describes the spread of the middle half of ordered numerical data.",
    plainLanguage: "The spread of the middle 50 percent of the data.",
    aqrUse: "Extension learners may use the IQR to compare spread while reducing the influence of extreme values.",
    questionStem: "The IQR shows that the middle half of the data spans ______.",
  },
  {
    term: "Margin of error",
    group: "Extension vocabulary",
    fullDefinition: "A margin of error is a range that expresses expected sampling uncertainty around an estimate, usually under stated assumptions and a chosen confidence level.",
    plainLanguage: "A range showing that a sample estimate is not exact.",
    aqrUse: "When surveys report a margin of error, extension learners will interpret close percentages more carefully.",
    questionStem: "The margin of error means the true value may be about ______ to ______.",
  },
  {
    term: "Random sample",
    group: "Extension vocabulary",
    fullDefinition: "A random sample is selected by a process that gives each eligible member of the population a known chance of being chosen.",
    plainLanguage: "A sample chosen by chance instead of convenience.",
    aqrUse: "You will compare random sampling with convenience sampling and explain what each design allows you to conclude.",
    questionStem: "This is or is not a random sample because ______.",
  },
  {
    term: "Skew",
    group: "Extension vocabulary",
    fullDefinition: "Skew describes a distribution that stretches farther on one side than the other because values are not balanced around the center.",
    plainLanguage: "The data lean or stretch more toward one side.",
    aqrUse: "You will use skew to explain why the mean and median may tell different stories.",
    questionStem: "The distribution is skewed toward ______ because ______.",
  },
  {
    term: "Variability",
    group: "Extension vocabulary",
    fullDefinition: "Variability is the degree to which data values differ from one another or from a typical value.",
    plainLanguage: "How spread out or different the values are.",
    aqrUse: "Extension learners compare groups not only by average but also by how consistent or spread out the values are.",
    questionStem: "This group shows more variability because ______.",
  },
];
